(() => {
  'use strict';
  const API=window.APP_CONFIG.API_URL;
  const state={items:[],query:'',page:1,perPage:4};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  async function api(action,data={}){const token=sessionStorage.getItem('mysiteAdminToken')||'';const response=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({mode:'facebookadmin',action,data,token})});const result=await response.json();if(!result.success)throw new Error(result.message||'ดำเนินการไม่สำเร็จ');return result.data}
  async function load(){const data=await api('list');state.items=data.items||[]}
  function filtered(){return state.items.filter(x=>String(x.poster||'').toLowerCase().includes(state.query.toLowerCase()))}
  function managerHtml(){const all=filtered(),pages=Math.max(1,Math.ceil(all.length/4));state.page=Math.min(state.page,pages);const rows=all.slice((state.page-1)*4,state.page*4).map(x=>`<tr><td>${esc(x.poster)}</td><td><code class="facebook-manager-code">${esc(x.embedCode)}</code></td><td>${esc(x.date)}</td><td><div class="facebook-manager-actions"><button class="newsletter-btn newsletter-edit" data-fb-edit="${x.rowNumber}">แก้ไข</button><button class="newsletter-btn newsletter-delete" data-fb-delete="${x.rowNumber}">ลบ</button></div></td></tr>`).join('')||'<tr><td colspan="4" style="text-align:center">ไม่พบรายการ</td></tr>';const nav=Array.from({length:pages},(_,i)=>`<button data-fb-page="${i+1}" class="${state.page===i+1?'active':''}">${i+1}</button>`).join('');return `<div class="facebook-manager"><div class="facebook-manager-toolbar"><b class="facebook-manager-total">จำนวนรายการทั้งหมด ${all.length} รายการ</b><input id="facebookManagerSearch" class="facebook-manager-search" value="${esc(state.query)}" placeholder="ค้นหาผู้โพสต์"><button id="facebookManagerAdd" class="newsletter-btn facebook-manager-add">+เพิ่มรายการ</button></div><div class="facebook-manager-table-wrap"><table class="facebook-manager-table"><thead><tr><th>ผู้โพสต์</th><th>โค้ดฝัง</th><th>วันที่</th><th>จัดการ</th></tr></thead><tbody>${rows}</tbody></table></div><div class="facebook-manager-pages">${nav}</div></div>`}
  function bind(){const q=document.getElementById('facebookManagerSearch');q?.addEventListener('input',e=>{const pos=e.target.selectionStart;state.query=e.target.value;state.page=1;rerender();const next=document.getElementById('facebookManagerSearch');next?.focus();next?.setSelectionRange(pos,pos)});document.getElementById('facebookManagerAdd')?.addEventListener('click',()=>openEditor());document.querySelectorAll('[data-fb-page]').forEach(b=>b.onclick=()=>{state.page=+b.dataset.fbPage;rerender()});document.querySelectorAll('[data-fb-edit]').forEach(b=>b.onclick=()=>openEditor(state.items.find(x=>x.rowNumber===+b.dataset.fbEdit)));document.querySelectorAll('[data-fb-delete]').forEach(b=>b.onclick=()=>remove(+b.dataset.fbDelete))}
  function rerender(){const box=Swal.getHtmlContainer();if(box){box.innerHTML=managerHtml();bind()}}
  async function openManager(){Swal.fire({title:'กำลังโหลด...',allowOutsideClick:false,didOpen:()=>Swal.showLoading()});try{await load();state.query='';state.page=1;await Swal.fire({title:'เพิ่ม/ลบ รายการโพสต์ Facebook',html:managerHtml(),width:'min(1200px,97vw)',showConfirmButton:false,showCloseButton:true,didOpen:bind})}catch(e){Swal.fire('เกิดข้อผิดพลาด',e.message,'error')}}
  function overlay(title,html){const popup=Swal.getPopup();if(!popup)return null;popup.querySelector('.facebook-action-overlay')?.remove();const layer=document.createElement('div');layer.className='newsletter-action-overlay facebook-action-overlay';layer.innerHTML=`<div class="newsletter-action-dialog"><h3>${esc(title)}</h3>${html}</div>`;popup.appendChild(layer);return layer}
  function validIframe(code){const doc=new DOMParser().parseFromString(code.trim(),'text/html'),frame=doc.body.firstElementChild;if(!frame||frame.tagName!=='IFRAME'||doc.body.children.length!==1)return false;try{const u=new URL(frame.getAttribute('src')||'');return u.protocol==='https:'&&u.hostname==='www.facebook.com'&&u.pathname==='/plugins/post.php'&&u.searchParams.has('href')}catch(_){return false}}
  function openEditor(item){const editing=!!item;const layer=overlay(editing?'แก้ไขโพสต์ Facebook':'เพิ่มโพสต์ Facebook',`<div class="newsletter-form facebook-manager-form"><label>ผู้โพสต์ *<input id="fbPoster" value="${esc(item?.poster||'')}"></label><label>โค้ดฝัง Facebook iframe *<textarea id="fbEmbed" placeholder="<iframe src=&quot;https://www.facebook.com/plugins/post.php?...&quot; ...></iframe>">${esc(item?.embedCode||'')}</textarea></label><div id="fbError" class="newsletter-action-error"></div><div class="newsletter-action-buttons"><button class="newsletter-btn newsletter-cancel" type="button">ยกเลิก</button><button class="newsletter-btn newsletter-add facebook-save" type="button">${editing?'บันทึกการแก้ไข':'เพิ่มรายการ'}</button></div></div>`);if(!layer)return;layer.querySelector('.newsletter-cancel').onclick=()=>layer.remove();layer.querySelector('.facebook-save').onclick=async()=>{const poster=layer.querySelector('#fbPoster').value.trim(),embedCode=layer.querySelector('#fbEmbed').value.trim(),error=layer.querySelector('#fbError'),button=layer.querySelector('.facebook-save');error.textContent='';if(!poster)return error.textContent='กรุณากรอกผู้โพสต์';if(!validIframe(embedCode))return error.textContent='โค้ดฝังต้องเป็น iframe จาก Facebook Post Plugin เท่านั้น';button.disabled=true;button.textContent='กำลังบันทึก...';try{await api('save',{rowNumber:item?.rowNumber||0,poster,embedCode});await load();document.dispatchEvent(new Event('facebook-admin-updated'));layer.remove();rerender()}catch(e){error.textContent='บันทึกไม่สำเร็จ: '+e.message;button.disabled=false;button.textContent=editing?'บันทึกการแก้ไข':'เพิ่มรายการ'}}}
  function remove(rowNumber){const layer=overlay('ยืนยันการลบ?',`<p>รายการโพสต์จะถูกลบออกจากชีต</p><div id="fbDeleteError" class="newsletter-action-error"></div><div class="newsletter-action-buttons"><button class="newsletter-btn newsletter-cancel">ยกเลิก</button><button class="newsletter-btn newsletter-delete facebook-confirm-delete">ลบ</button></div>`);if(!layer)return;layer.querySelector('.newsletter-cancel').onclick=()=>layer.remove();layer.querySelector('.facebook-confirm-delete').onclick=async()=>{const button=layer.querySelector('.facebook-confirm-delete'),error=layer.querySelector('#fbDeleteError');button.disabled=true;button.textContent='กำลังลบ...';try{await api('delete',{rowNumber});await load();document.dispatchEvent(new Event('facebook-admin-updated'));layer.remove();rerender()}catch(e){error.textContent='ลบไม่สำเร็จ: '+e.message;button.disabled=false;button.textContent='ลบ'}}}
  function initializeFacebookManager(){const button=document.getElementById('manageFacebookButton');if(button&&!button.dataset.managerReady){button.dataset.managerReady='1';button.addEventListener('click',openManager)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initializeFacebookManager,{once:true});else initializeFacebookManager();
})();
