(()=>{'use strict';
const API=window.APP_CONFIG.API_URL + '?mode=media';let items=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),safe=v=>{const u=String(v||'').trim();return /^https?:\/\//i.test(u)?u.replace(/^http:\/\//i,'https://'):''};
const filters=()=>({title:document.getElementById('mediaTitleFilter'),subject:document.getElementById('mediaSubjectFilter'),grade:document.getElementById('mediaGradeFilter'),mediaType:document.getElementById('mediaTypeFilter')});
function closeDetail(){document.querySelector('.media-detail-backdrop')?.remove();document.body.classList.remove('media-modal-open')}
function detail(x){const image=safe(x.image),file=safe(x.fileUrl),layer=document.createElement('div');layer.className='media-detail-backdrop';layer.innerHTML=`<div class="media-detail" role="dialog" aria-modal="true"><button class="media-detail-close" type="button" aria-label="ปิด">×</button>${image?`<img class="media-detail-image" src="${esc(image)}" alt="${esc(x.title)}">`:'<div class="media-detail-no-image">📚</div>'}<div class="media-detail-info"><div><b>เรื่อง</b><span>${esc(x.title||'-')}</span></div><div><b>วิชา</b><span>${esc(x.subject||'-')}</span></div><div><b>ชั้น</b><span>${esc(x.grade||'-')}</span></div><div><b>ประเภทสื่อ</b><span>${esc(x.mediaType||'-')}</span></div><div><b>เจ้าของผลงาน</b><span>${esc(x.owner||'-')}</span></div>${x.date?`<div><b>วันที่</b><span>${esc(x.date)}</span></div>`:''}${file?`<a class="media-detail-download" href="${esc(file)}" target="_blank" rel="noopener">เปิดไฟล์</a>`:''}</div></div>`;layer.onclick=e=>{if(e.target===layer)closeDetail()};layer.querySelector('button').onclick=closeDetail;document.body.appendChild(layer);document.body.classList.add('media-modal-open')}
function selected(){const f=filters(),q=String(document.getElementById('mediaSearch')?.value||'').trim().toLocaleLowerCase('th');return items.filter(x=>(!f.title.value||x.title===f.title.value)&&(!f.subject.value||x.subject===f.subject.value)&&(!f.grade.value||x.grade===f.grade.value)&&(!f.mediaType.value||x.mediaType===f.mediaType.value)&&(!q||[x.title,x.subject,x.grade,x.mediaType,x.owner].join(' ').toLocaleLowerCase('th').includes(q)))}
function render(){const grid=document.getElementById('mediaGrid'),shown=selected();if(!shown.length){grid.innerHTML='<div class="media-empty">ไม่พบรายการตามตัวกรองที่เลือก</div>';return}grid.innerHTML=shown.map((x,i)=>{const image=safe(x.image),idx=items.indexOf(x);return `<article class="media-card"><div class="media-card-image" tabindex="0" role="button" data-media-index="${idx}" aria-label="ดูรายละเอียด ${esc(x.title)}">${image?`<img src="${esc(image)}" alt="${esc(x.title||`สื่อรายการที่ ${i+1}`)}" loading="lazy">`:'<div class="media-no-image">📚</div>'}</div><div class="media-card-body"><h2>${esc(x.title||'ไม่ระบุชื่อเรื่อง')}</h2><dl><div><dt>วิชา</dt><dd>${esc(x.subject||'-')}</dd></div><div><dt>ชั้น</dt><dd>${esc(x.grade||'-')}</dd></div><div><dt>ประเภทสื่อ</dt><dd>${esc(x.mediaType||'-')}</dd></div><div><dt>เจ้าของผลงาน</dt><dd>${esc(x.owner||'-')}</dd></div></dl></div></article>`}).join('');grid.querySelectorAll('[data-media-index]').forEach(el=>{const open=()=>detail(items[+el.dataset.mediaIndex]);el.onclick=open;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function fill(select,key){const current=select.value,values=[...new Set(items.map(x=>x[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th'));select.innerHTML='<option value="">ทั้งหมด</option>'+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');select.value=values.includes(current)?current:'';select.disabled=false;if(!select.dataset.bound){select.onchange=render;select.dataset.bound='1'}}
async function load(){const status=document.getElementById('mediaStatus'),grid=document.getElementById('mediaGrid');try{const r=await fetch(API+'&_t='+Date.now(),{cache:'no-store'}),j=await r.json();if(!r.ok||j.success===false)throw new Error(j.message||'โหลดข้อมูลไม่สำเร็จ');items=(Array.isArray(j.items)?j.items:[]).map(x=>({mediaType:String(x.mediaType||'').trim(),title:String(x.title||'').trim(),subject:String(x.subject||'').trim(),grade:String(x.grade||'').trim(),fileUrl:String(x.fileUrl||'').trim(),image:String(x.image||'').trim(),owner:String(x.owner||'').trim(),date:String(x.date||'').trim(),area:String(x.area||'').trim()}));status.hidden=true;Object.entries(filters()).forEach(([key,el])=>fill(el,key));const search=document.getElementById('mediaSearch');if(search&&!search.dataset.bound){search.oninput=render;search.dataset.bound='1'};render()}catch(e){status.hidden=true;grid.innerHTML=`<div class="media-error">โหลดรายการไม่สำเร็จ<br>${esc(e.message)}</div>`}}
document.addEventListener('DOMContentLoaded',load);document.addEventListener('media-admin-updated',load);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});})();
