(()=>{
'use strict';
const API=(window.APP_CONFIG&&window.APP_CONFIG.API_URL)||'https://script.google.com/macros/s/AKfycbxba2Enfzaz4wu7supLpkW2V-3aQLk4AG6KtPjc6GczcifG4J7wXpcE85pmAZsoKXdBhg/exec';
const TYPES=['การเรียนรู้ตลอดชีวิต','การเรียนรู้เพื่อพัฒนาตนเอง','การเรียนรู้เพื่อคุณวุฒิตามระดับ','อื่นๆ'];
const state={items:[],query:'',page:1};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function validUrl(v){try{return ['http:','https:'].includes(new URL(v).protocol)}catch(_){return false}}
async function api(action,data={}){const token=sessionStorage.getItem('mysiteAdminToken')||'',r=await fetch(API,{method:'POST',cache:'no-store',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({mode:'reportadmin',action,data,token})}),j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'ดำเนินการไม่สำเร็จ');return j.data;}
async function load(){const d=await api('list');state.items=Array.isArray(d?.items)?d.items:(Array.isArray(d)?d:[]);}
function filtered(){const q=state.query.trim().toLowerCase();return q?state.items.filter(x=>`${x.order} ${x.title} ${x.reporter} ${x.type}`.toLowerCase().includes(q)):state.items;}
function tableHtml(){const all=filtered(),pages=Math.max(1,Math.ceil(all.length/8));state.page=Math.min(state.page,pages);const rows=all.slice((state.page-1)*8,state.page*8).map(x=>`<tr><td>${esc(x.order)}</td><td>${esc(x.title)}</td><td>${esc(x.reporter)}</td><td>${esc(x.type)}</td><td>${x.fileUrl?`<a class="rp-download" href="${esc(x.fileUrl)}" target="_blank" rel="noopener noreferrer">ดาวน์โหลด</a>`:'-'}</td><td><div class="rp-actions"><button class="rp-btn rp-edit" type="button" data-rp-edit="${x.rowNumber}">แก้ไข</button><button class="rp-btn rp-delete" type="button" data-rp-delete="${x.rowNumber}">ลบ</button></div></td></tr>`).join('')||'<tr><td colspan="6" style="text-align:center;padding:30px;color:#64748b">ยังไม่มีรายการ</td></tr>';const nav=Array.from({length:pages},(_,i)=>`<button type="button" data-rp-page="${i+1}" class="${state.page===i+1?'active':''}">${i+1}</button>`).join('');return `<div class="rp-manager"><div class="rp-toolbar"><b class="rp-total">จำนวน ${all.length} รายการ</b><input id="rpSearch" class="rp-search" value="${esc(state.query)}" placeholder="ค้นหารายงาน"><button id="rpAdd" class="rp-btn rp-add" type="button">+ เพิ่มรายงาน</button></div><div class="rp-table-wrap"><table class="rp-table"><thead><tr><th>ลำดับ</th><th>เรื่อง</th><th>ผู้รายงาน</th><th>ประเภทงาน</th><th>ดาวน์โหลดไฟล์</th><th>จัดการ</th></tr></thead><tbody>${rows}</tbody></table></div><div class="rp-pages">${nav}</div></div>`;}
function rerender(){const c=document.querySelector('.swal2-html-container');if(c){c.innerHTML=tableHtml();bind();}}
function bind(){const q=document.getElementById('rpSearch');q?.addEventListener('input',e=>{const p=e.target.selectionStart;state.query=e.target.value;state.page=1;rerender();const n=document.getElementById('rpSearch');n?.focus();n?.setSelectionRange(p,p)});document.getElementById('rpAdd')?.addEventListener('click',()=>editor());document.querySelectorAll('[data-rp-page]').forEach(b=>b.onclick=()=>{state.page=+b.dataset.rpPage;rerender()});document.querySelectorAll('[data-rp-edit]').forEach(b=>b.onclick=()=>editor(state.items.find(x=>x.rowNumber===+b.dataset.rpEdit)));document.querySelectorAll('[data-rp-delete]').forEach(b=>b.onclick=()=>remove(+b.dataset.rpDelete));}
function closeOverlay(layer){const p=Swal.getPopup();if(layer)layer.remove();if(p&&!p.querySelector('.rp-action-editor'))p.classList.remove('rp-editor-open');}
function overlay(title,body,extraClass=''){const p=Swal.getPopup();if(!p)return null;p.querySelector('.rp-action')?.remove();const isEditor=String(extraClass||'').split(/\s+/).includes('rp-action-editor');p.classList.toggle('rp-editor-open',isEditor);const l=document.createElement('div');l.className=('rp-overlay rp-action '+extraClass).trim();l.innerHTML=`<div class="rp-dialog"><h3>${esc(title)}</h3>${body}</div>`;p.appendChild(l);return l;}
function readFile(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);if(file.size>15*1024*1024)return reject(new Error('ไฟล์มีขนาดใหญ่เกิน 15 MB'));const r=new FileReader();r.onload=()=>resolve({dataUrl:r.result,fileName:file.name});r.onerror=()=>reject(new Error('อ่านไฟล์ไม่สำเร็จ'));r.readAsDataURL(file);});}
function editor(item){let upload=null;const editing=!!item;const options=TYPES.map(v=>`<option value="${esc(v)}" ${item?.type===v?'selected':''}>${esc(v)}</option>`).join('');const l=overlay(editing?'แก้ไขรายงาน':'เพิ่มรายงาน',`<div class="rp-form"><label>เรื่อง *<input id="rpTitle" value="${esc(item?.title||'')}" placeholder="ระบุเรื่องรายงาน"></label><label>ผู้รายงาน *<input id="rpReporter" value="${esc(item?.reporter||'')}" placeholder="ชื่อ นามสกุล"></label><label>ประเภทงาน *<select id="rpType"><option value="">-- เลือกประเภทงาน --</option>${options}</select></label><div class="rp-upload-box"><label>URL ไฟล์<input id="rpFileUrl" type="url" value="${esc(item?.fileUrl||'')}" placeholder="https://..."></label><label>หรืออัปโหลดไฟล์<input id="rpFile" type="file"></label><span class="rp-hint">รองรับไฟล์ทั่วไป ขนาดไม่เกิน 15 MB</span><span id="rpFileName" class="rp-file-name">${item?.fileUrl?'มีไฟล์เดิมแล้ว':''}</span></div><div id="rpError" class="rp-error"></div><div class="rp-form-actions"><button class="rp-btn rp-cancel" type="button">ยกเลิก</button><button class="rp-btn rp-save" type="button">${editing?'บันทึกการแก้ไข':'เพิ่มรายงาน'}</button></div></div>`,'rp-action-editor');if(!l)return;l.querySelector('.rp-cancel').onclick=()=>closeOverlay(l);l.querySelector('#rpFile').onchange=async e=>{const er=l.querySelector('#rpError'),name=l.querySelector('#rpFileName');try{upload=await readFile(e.target.files[0]);name.textContent=upload?`เลือกไฟล์: ${upload.fileName}`:'';er.textContent='';}catch(x){upload=null;e.target.value='';name.textContent='';er.textContent=x.message;}};l.querySelector('.rp-save').onclick=async()=>{const er=l.querySelector('#rpError'),b=l.querySelector('.rp-save'),data={rowNumber:item?.rowNumber||0,title:l.querySelector('#rpTitle').value.trim(),reporter:l.querySelector('#rpReporter').value.trim(),type:l.querySelector('#rpType').value.trim(),fileUrl:l.querySelector('#rpFileUrl').value.trim(),fileData:upload?.dataUrl||'',fileName:upload?.fileName||''};er.textContent='';if(!data.title)return er.textContent='กรุณากรอกเรื่อง';if(!data.reporter)return er.textContent='กรุณากรอกผู้รายงาน';if(!TYPES.includes(data.type))return er.textContent='กรุณาเลือกประเภทงาน';if(!data.fileData&&!data.fileUrl)return er.textContent='กรุณาระบุ URL หรืออัปโหลดไฟล์';if(data.fileUrl&&!validUrl(data.fileUrl))return er.textContent='URL ไฟล์ไม่ถูกต้อง';b.disabled=true;b.textContent='กำลังบันทึก...';try{await api('save',data);await load();document.dispatchEvent(new Event('report-admin-updated'));closeOverlay(l);rerender();}catch(x){er.textContent='บันทึกไม่สำเร็จ: '+x.message;b.disabled=false;b.textContent=editing?'บันทึกการแก้ไข':'เพิ่มรายงาน';}};}
function remove(rowNumber){const item=state.items.find(x=>x.rowNumber===rowNumber);const l=overlay('ยืนยันการลบ?',`<p style="text-align:center">ต้องการลบรายงาน <b>${esc(item?.title||'')}</b> หรือไม่</p><div id="rpDeleteError" class="rp-error"></div><div class="rp-form-actions"><button class="rp-btn rp-cancel" type="button">ยกเลิก</button><button class="rp-btn rp-confirm-delete" type="button">ลบ</button></div>`);if(!l)return;l.querySelector('.rp-cancel').onclick=()=>closeOverlay(l);l.querySelector('.rp-confirm-delete').onclick=async()=>{const b=l.querySelector('.rp-confirm-delete'),er=l.querySelector('#rpDeleteError');b.disabled=true;b.textContent='กำลังลบ...';try{await api('delete',{rowNumber});await load();document.dispatchEvent(new Event('report-admin-updated'));closeOverlay(l);rerender();}catch(x){er.textContent='ลบไม่สำเร็จ: '+x.message;b.disabled=false;b.textContent='ลบ';}};}
async function open(){Swal.fire({title:'กำลังโหลดข้อมูลรายงาน...',allowOutsideClick:false,didOpen:()=>Swal.showLoading()});try{await load();await Swal.fire({title:'จัดการรายงานผลการปฏิบัติการ',html:tableHtml(),width:'min(1250px,98vw)',showConfirmButton:false,showCloseButton:true,didOpen:bind});}catch(e){Swal.fire({icon:'error',title:'โหลดข้อมูลไม่สำเร็จ',text:e.message});}}
document.addEventListener('admin:manage-data',e=>{if(e.detail?.page==='report')open();});
})();
