(() => {
  'use strict';
  const API_URL=window.APP_CONFIG.API_URL;
  const track=document.getElementById('shopActivityTrack');if(!track)return;
  let items=[],page=0,perPage=3,timer=null;
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
  const openShop=()=>window.open('shopactivity.html','_blank','noopener');
  const cardsPerPage=()=>window.innerWidth<=620?1:window.innerWidth<=900?2:3;
  async function load(){try{let json;if(window.SiteFast){json=await window.SiteFast.fetchMode('learning',{action:'getActivities'},{key:'learning-activities-v1',ttl:120000})}else{const url=new URL(API_URL);url.searchParams.set('mode','learning');url.searchParams.set('action','getActivities');const response=await fetch(url.toString(),{cache:'default'});json=await response.json();if(!response.ok)throw new Error(`HTTP ${response.status}`)}if(json?.success===false)throw new Error(json?.message||'โหลดข้อมูลไม่สำเร็จ');items=Array.isArray(json?.data)?json.data:Array.isArray(json)?json:[];render();restart()}catch(error){track.innerHTML=`<div class="shopactivity-loading">โหลดกิจกรรมไม่สำเร็จ: ${esc(error.message)}</div>`}}
  function render(){if(!items.length){track.innerHTML='<div class="shopactivity-loading">ยังไม่มีกิจกรรม</div>';return}track.innerHTML=items.map(item=>`<article class="shopactivity-card" tabindex="0" role="link" aria-label="เปิดกิจกรรม ${esc(item.title)}"><img class="shopactivity-image" src="${esc(item.image1||'')}" alt="${esc(item.title)}" loading="lazy"><div class="shopactivity-body"><h3>${esc(item.title)}</h3><div class="shopactivity-meta">Point: ${esc(item.hours||'0')} Point</div><div class="shopactivity-meta">รูปแบบ: ${esc(item.learningType||'-')}</div><div class="shopactivity-meta">วันที่: ${esc(item.activityDate||'-')}</div></div></article>`).join('');track.querySelectorAll('.shopactivity-card').forEach(card=>{card.onclick=openShop;card.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openShop()}}});update(true)}
  function update(reset){const old=perPage;perPage=cardsPerPage();if(reset||old!==perPage)page=0;const count=Math.max(1,Math.ceil(items.length/perPage));page=Math.max(0,Math.min(page,count-1));const card=track.querySelector('.shopactivity-card');if(card)track.style.transform=`translateX(-${page*perPage*(card.getBoundingClientRect().width+22)}px)`;const dots=document.getElementById('shopActivityDots');dots.innerHTML=Array.from({length:count},(_,i)=>`<button class="shopactivity-dot ${i===page?'active':''}" type="button" data-page="${i}" aria-label="หน้าที่ ${i+1}"></button>`).join('');dots.querySelectorAll('[data-page]').forEach(dot=>dot.onclick=()=>{page=Number(dot.dataset.page);update(false);restart()});document.getElementById('shopActivityPrev').disabled=page===0;document.getElementById('shopActivityNext').disabled=page===count-1}
  function move(step){const count=Math.max(1,Math.ceil(items.length/perPage));page=(page+step+count)%count;update(false);restart()}function restart(){clearInterval(timer);if(items.length>perPage)timer=setInterval(()=>move(1),6000)}
  document.getElementById('shopActivityPrev').onclick=()=>move(-1);document.getElementById('shopActivityNext').onclick=()=>move(1);window.addEventListener('resize',()=>update(false));if(window.SiteFast)window.SiteFast.whenNear('learningBaseModule',load);else load();
})();
